### ISSUE TITLE
Errore durante la conversione del file xlsx

### ISSUE THREAD

**Issue by ghost** [Jacotsu/ofxstatement-intesasp#1]
Ciao, ho provato ad usare questo plugin, ho scaricato i movimenti del mio conto ma ottengo il seguente errore:

```
ofxstatement convert -t IntesaSP Movimenti_Conto_10042022.xlsx movimenti.ofx
Traceback (most recent call last):
  File "/home/dan/.local/bin/ofxstatement", line 8, in <module>
    sys.exit(run())
  File "/home/dan/.local/lib/python3.9/site-packages/ofxstatement/tool.py", line 205, in run
    return args.func(args)
  File "/home/dan/.local/lib/python3.9/site-packages/ofxstatement/tool.py", line 176, in convert
    statement = parser.parse()
  File "/home/dan/.local/lib/python3.9/site-packages/ofxstatement/plugins/intesaSP.py", line 54, in parse
    return super(IntesaSanPaoloXlsxParser, self).parse()
  File "/home/dan/.local/lib/python3.9/site-packages/ofxstatement/parser.py", line 46, in parse
    stmt_line = self.parse_record(line)
  File "/home/dan/.local/lib/python3.9/site-packages/ofxstatement/plugins/intesaSP.py", line 64, in parse_record
    stat_line.trntype = IntesaSanPaoloXlsxParser._get_transaction_type(mov)
  File "/home/dan/.local/lib/python3.9/site-packages/ofxstatement/plugins/intesaSP.py", line 120, in _get_transaction_type
    return trans_map[movimento.descrizione]
KeyError: 'Pagamento adue'
```

**Comment by Jacotsu** [comment]
ciao, quell'errore è dovuto al fatto che il tipo di pagamento non è presente nel dizionario delle transazioni (https://github.com/Jacotsu/ofxstatement-intesasp/blob/master/src/ofxstatement/plugins/intesaSP.py#L102).

se sei in grado di installare il pacchetto da github posso pushare un fix

**Comment by ghost** [comment]
Grazie, ho aggiunto questi e funziona:

```
'Pagamento adue': 'DEBIT',
'Pagamento delega f24 via internet banking': 'PAYMENT',
'Bonifico in euro verso ue/sepa canale telem.': 'PAYMENT',
'Accredito bonifico istantaneo': 'XFER'
```

Non so se i codici son giusti però

**Comment by Jacotsu** [comment]
> Grazie, ho aggiunto questi e funziona:
> 
> ```
> 'Pagamento adue': 'DEBIT',
> 'Pagamento delega f24 via internet banking': 'PAYMENT',
> 'Bonifico in euro verso ue/sepa canale telem.': 'PAYMENT',
> 'Accredito bonifico istantaneo': 'XFER'
> ```
> 
> Non so se i codici son giusti però

Credo che questi siano codici più appropriati in base a quello che c'è scritto qui https://github.com/kedder/ofxstatement/blob/bcabc440c7bcf806e8d00fbd47338d4efd84ef70/src/ofxstatement/statement.py#L11
```
'Pagamento adue': 'PAYMENT',
'Pagamento delega f24 via internet banking': 'PAYMENT',
'Bonifico in euro verso ue/sepa canale telem.': 'PAYMENT',
'Accredito bonifico istantaneo': 'DEP'
```

**Comment by a-lberto** [comment]
Scusate non avevo letto l'issue e ho direttamente fatto una PR #2 , ora a me funziona ed avevo lo stesso errore di @daniele123321
