### ISSUE TITLE
Warning!!!

### ISSUE THREAD

**Issue by Alfystar** [Jacotsu/ofxstatement-intesasp#5]
Ti scrivo per notificarti che Intesa San Paolo, almeno sull'app cellulare, sta iniziando a usare un altro formato di Excel:
New format:
![Screenshot_20220922_095353-1](https://user-images.githubusercontent.com/32840211/191690998-ccdf88f0-c034-4cfd-90d8-585c9c793cc1.png)

Questo nuovo formato sotto certi punti di vista è anche più comodo, poiché contiene una prima categorizzazione delle spese, e ogni transazione ha la sua valuta, cosa non scontata, però lo script attuale non funziona.
Per ora da Web, continua a scaricare il precedente modello, ma penso sarebbe una buona idea iniziare uno sviluppo per il nuovo formato e aggiungere da terminale la scelta tra il tipo di modello inserito.

Durante i ritagli se riesco ci lavorerò anche io, ma sarei felice di aiutarti :smile:.

PS
Alla fine hai aggiornato la versione su PIP?

**Comment by Jacotsu** [comment]
purtroppo son stato impegnato, appena riesco a testarlo come si deve lo faccio.

Riguardo il nuovo formato: conviene aspettare e vedere cosa fanno con la versione web perchè se non ricordo male già da prima c'erano 2 formati di file excel:
- Il file dei movimenti
- il file di bilancio

**Comment by Alfystar** [comment]
Ciao jacotsu, ti scrivo qui per evitare di aprire un altro issue.
Volevo chiederti, che ne pensi di modificare l'ottenimento della data usando il campo "Data valuta" invece del campo "Data contabile" ?
In fondo ha più senso sapere quando sono stati spesi (onestamente non capisco perchè ci sia sempre questo ritardo)
E coprire così anche il secondo blocco di operazioni, quelle non ancora contabilizzate.

Che ne pensi?

**Comment by Jacotsu** [comment]
> e il secondo bloc

non mi sembra una buona idea perchè data valuta e data contabile sono 2 cose diverse.
Generalmente la data valuta indica la data in cui l'operazione è avvenuta.
La data contabile è la data in cui l'operazione è effetivamente contabilizzata e l'eventuale denaro diviene disponibile.

Per esempio se versi un assegno la data valuta indica il giorno in cui l'hai versato, ma quei soldi sono disponibili solo dopo esser stati contabilizzati.
Quindi capirai che potrebbe dar problemi nei software di contabilizzazione l'utilizzo della data valuta

**Comment by Alfystar** [comment]
Ottima osservazione
Ho fatto bene a parlarne prima qui 😁

**Comment by Alfystar** [comment]
Ciao, senti, ma alla fine hai lasciato su PIP tutte le modifiche? Ormai direi che abbiamo raggiunto una nuova soglia di stabilità

**Comment by Alfystar** [comment]
Ciao, buon giorno :smile: 

Purtroppo il giorno è arrivato, proprio oggi scaricando i movimenti da Browser, ho ottenuto la lista movimenti diversa, come era successo anche al cell.
Cmq a sinistra il nuovo formato browser, mentre a destra il formato precedente:
![image](https://user-images.githubusercontent.com/32840211/222134093-2d8c90b2-4734-4402-9a8b-d50c2f487123.png)

Come procediamo? Aggiorniamo il codice "rimuovendo" il supporto al precedente formato o hai in mente un altra idea?

Non è neanche come al Cellulare che ritorna molte più informazioni, si direbbe quasi parziale, non sò se è definitivo

**Comment by Jacotsu** [comment]
> lista movim

Credo che la cosa più furba sia fare un check sugli header delle tabelle per vedere quale versione dell'xls abbiamo e poi processare di conseguenza

**Comment by Alfystar** [comment]
Ma lo sai che ho pensato anche io la stessa cosa in questi giorni!

Questo weekend e la prossima settimana - credo avrò poco tempo per mettermi a programmare, ma se a lavoro si crea un buco ci provo, tu hai già fatto qualcosa?

Cmq, se sei d'accordo, penso fai prima ad accettarmi nel tuo repository, se ti fidi del mio lavoro, così evitiamo di fare ogni volta fork e pull request
Che ne dici?

**Comment by Jacotsu** [comment]
Ok
