### ISSUE TITLE
Fixati errori e cambiate alcune tipologie di transazione

### ISSUE THREAD

**Issue by Jacotsu** [Jacotsu/ofxstatement-intesasp#9]
@Alfystar ciao, ho controllato il codice e fatto alcune modifiche.

Ho fatto delle piccole migliorie e nel commit [b513243](https://github.com/Jacotsu/ofxstatement-intesasp/commit/b513243e2581d540cff650a164b6b2822ef1438e) ho modificato alcune categorie con tipologie di transazione più adeguate.

Fai un paio di test e fammi sapere se hai problemi, così carico il pacchetto su pypi

**Comment by Alfystar** [comment]
Contaci!! 
dammi un paio di giorni così accumulo transazioni 😁😁😁

**Comment by Alfystar** [comment]
Ciao @Jacotsu 
Ho testato il tuo codice, mi piace molto quello che hai scritto!

Nel commit 68938e1 ho tolto qualche accapo in eccesso e ho riformattato il codice con il tool automatico, ah, anche se ancora non lo usiamo, ho salvato i settings in una variabile di classe, penso sia più pulito e future proof.
L'unica cosa concettualmente nuova che ho fatto è stata aggiungere ai due try-exept anche il ValueError, che nel mio caso impediva l'esecuzione dello script.

Le categorie mi sembrano migliori di prima :laughing:.

Ti direi di darmi qualche altro giorno così accumulo altre transazioni, ma direi che con queste ultime modifiche siamo pronti a rilasciarlo su PIP :smile:

**Comment by Jacotsu** [comment]
> Ciao @Jacotsu Ho testato il tuo codice, mi piace molto quello che hai scritto!
> 
> Nel commit [68938e1](https://github.com/Jacotsu/ofxstatement-intesasp/commit/68938e17568168acfb973b60fc6987835fd0bd9f) ho tolto qualche accapo in eccesso e ho riformattato il codice con il tool automatico, ah, anche se ancora non lo usiamo, ho salvato i settings in una variabile di classe, penso sia più pulito e future proof. L'unica cosa concettualmente nuova che ho fatto è stata aggiungere ai due try-exept anche il ValueError, che nel mio caso impediva l'esecuzione dello script.
> 
> Le categorie mi sembrano migliori di prima laughing.
> 
> Ti direi di darmi qualche altro giorno così accumulo altre transazioni, ma direi che con queste ultime modifiche siamo pronti a rilasciarlo su PIP smile

Se usi un tool automatico di formattazione puoi caricare la configurazione sul repo così usiamo entrambi la stessa formattazione.
Tieni conto però che gli a capo non li ho messi a caso, servono per rispettare il limite massimo di 79 caratteri, così come specificato dalla [PEP8](https://peps.python.org/pep-0008/#maximum-line-length)

**Comment by Alfystar** [comment]
Uso il tool integrato in Pycharm, scarico la formattazione e la aggiungo volentieri 😄 

Per quanto riguarda il limite massimo di caratteri, io sto seguendo la filosofia di Linus che qualche anno fa decise che limitare il codice del kernel a 80 caratteri fosse datato e non in linea con le dimensioni dei monitor contemporanei.
https://www.phoronix.com/news/Linux-Kernel-Deprecates-80-Col
Io ormai uso 120 caratteri o 150, dipende dal progetto, nei miei monitor anche 100 caratteri sono poco più di metà schermo, ma se vuoi torno indietro e ci allineiamo a 80 senza problemi 👍

**Comment by Jacotsu** [comment]
> Uso il tool integrato in Pycharm, scarico la formattazione e la aggiungo volentieri smile
> 
> Per quanto riguarda il limite massimo di caratteri, io sto seguendo la filosofia di Linus che qualche anno fa decise che limitare il codice del kernel a 80 caratteri fosse datato e non in linea con le dimensioni dei monitor contemporanei. https://www.phoronix.com/news/Linux-Kernel-Deprecates-80-Col Io ormai uso 120 caratteri o 150, dipende dal progetto, nei miei monitor anche 100 caratteri sono poco più di metà schermo, ma se vuoi torno indietro e ci allineiamo a 80 senza problemi +1

Si, capisco. Anche io uso 120 caratteri su linguaggi come java, però su python cerco di rispettare la PEP8.

Tra l'altro stare sugli 80 caratteri mi permette di fare split screen senza avere un doppio monitor
![image](https://user-images.githubusercontent.com/20172693/236175316-dfc7e1d4-1684-47e4-b713-b5b2f16e9148.png)

**Comment by Alfystar** [comment]
Dai si, mi hai convinto, allora ora modifico le impostazioni per avere gli 80 caratteri e poi carico il file di configurazione 😊

**Comment by Jacotsu** [comment]
Caricato pacchetto su pypi

**Comment by Alfystar** [comment]
Grande, appena ho un momento verifico se funziona e cerco di ottenere il formattatore automatico, purtroppo in questi giorni il lavoro è stato incalzante.

Ma bel lavoro e bella squadra! 😊

**Comment by Alfystar** [comment]
> Caricato pacchetto su pypi

Verificato ora il funzionamento da PIP, con me funziona 😄 
Staremo a vedere cosa altro si inventeranno quelli di intesa, noi saremo pronti 😉
